CREATE USER C##sKauro IDENTIFIED BY mypw123
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp;


    GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO C##sKauro;

    GRANT CONNECT, RESOURCE TO C##sKauro;

    GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO C##sKauro;

    ALTER USER C##sKauro QUOTA UNLIMITED ON users;

    